### ISSUE TITLE
Narrowband error

### ISSUE THREAD

**Issue by andrewfam** [watson-developer-cloud/python-sdk#105]
Trying the below on an 8k sample rate still doesn't work.
json.dumps(speech_to_text.recognize(afile, content_type='audio/wav', timestamps=True), indent=2, model='en-UK_NarrowbandModel')

WatsonException: Error: This 8000hz audio input requires a narrow band model.  See https://stream.watsonplatform.net/speech-to-text/api/v1/models for a list of available models., Code: 400

I can upload the file through the link given above though

**Comment by jsstylos** [comment]
Hi, do you have an example of a file that fails in the Python SDK but works elsewhere? What's the link that you can upload the file through?

**Comment by celamb4** [comment]
I'm having an issue with narrowband model as well. However, I can make the request but get an empty return. If I try with the regular model it says to specify narroband. If I specify narrowband it comes back empty. Let me know if I shjould open a different issue. 

NOTE: I know the audio works with narroband because I tested it with the bluemix demo app. https://speech-to-text-demo.mybluemix.net/

`>>> speech_to_text.recognize(audio, content_type='audio/wav', model='en-US_NarrowbandModel') 
{u'results': [], u'result_index': 0}
`

`speech_to_text.recognize(audio, content_type='audio/wav') 
raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: This 8000hz audio input requires a narrow band model.  See https://stream.watsonplatform.net/speech-to-text/api/v1/models for a list of available models., Code: 400
`

**Comment by celamb4** [comment]
Additional information.

> audio = open('recoding0.wav', 'rb')
> speech_to_text = SpeechToText(username=username, password=password)>>> print(json.dumps(speech_to_text.recognize(audio, content_type='audio/wav', word_confidence=True, model='en-US_NarrowbandModel'), indent=2))
> {
>   "results": [], 
>   "result_index": 0
> }

**Comment by jsstylos** [comment]
@celamb4 Do you have a file we can use to reproduce this error?

**Comment by celamb4** [comment]
[recoding0.zip](https://github.com/watson-developer-cloud/python-sdk/files/592884/recoding0.zip)

**Comment by celamb4** [comment]
Also tried by posting a request. Here is the output. 
Thanks for the quick response!

```
>>> response = requests.post("https://stream.watsonplatform.net/speech-to-text/api/v1/recognize", auth=(username, password), headers = {"content-type": "audio/wav"}, data=audio, params={"model": 'en-US_NarrowbandModel'})

>>> response.text
u'{\n   "results": [], \n   "result_index": 0\n}'

```

**Comment by jsstylos** [comment]
Thanks @celamb4 . Got the audio file to work using the demo (which uses websockets through the Node SDK), and got the same empty results that you did using the Python SDK and Curl:

```
curl -X POST -u "username":"password" \
--header "Content-Type: audio/wav" \
--data-binary @recoding0.wav \
"https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_NarrowbandModel"
```

I'll investigate further with the Speech to Text service team.

**Comment by jsstylos** [comment]
Ok, the issue is that the command needs `continuous=true`; otherwise it defaults to `continuous=false`, which stops sending audio after the first silence. In this file it must detect some noise before the first recognized word, then more silence which triggers the end of the recording. The Python code looks like:

```
with open(join(dirname(__file__), 'recoding0.wav'), 'rb') as audio_file:
    print(json.dumps(speech_to_text.recognize(
        audio_file, content_type='audio/wav', timestamps=True, word_confidence=True, model='en-US_NarrowbandModel',
        continuous=True), indent=2))
```

**Comment by jsstylos** [comment]
(The default of `continuous=false` will get changed in the next major revision of the Speech to Text API.)

**Comment by celamb4** [comment]
Worked like a charm. Thank you @jsstylos
