### ISSUE TITLE
Confusion in README for using VCAP_SERVICES

### ISSUE THREAD

**Issue by gkumbhat** [watson-developer-cloud/python-sdk#168]
The way it is implemented in python-sdk, there is a confusion in the python-sdk README. It says :
```
If you run your app in Bluemix, you don't need to specify the username and password. In that case, the SDK uses the VCAP_SERVICES environment variable to load the credentials.
```
However, if somebody want to use the `VCAP_SERVICES` path then the username and passwords needs to be `YOUR SERVICE USERNAME` and `YOUR SERVICE PASSWORD` respectively in their app because it is doing string match on these to get the creds automatically. So if somebody puts something else into these variables then it is not able to take the values automatically from bluemix.

**Comment by jsstylos** [comment]
If users are intentionally using VCAP_SERVICES then the username and password should not be specified at all -- YOUR SERVICE USERNAME and YOUR SERVICE PASSWORD are intentionally ignored so that users get the right error message if they accidentally leave it in (and so the examples can easily function as integration tests).
