### ISSUE TITLE
The python-sdk is incompatible with a Permuation of Korean Laptop / Korean Code Page and Python 3

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/python-sdk#18]
Although it is ok with a Korean Laptop / Korean Code Page and Python 2.
Talking to my Korean colleagues I have learnt that this is quire common for pip packages, which is why they stick to Python 2. The strange thing is that the other packages they installed (django and request), were both OK. 
Short term fix is a note in the readme. Long term fix is to modify the code that breaks using the Korean Python 3 permutation.

**Comment by jsstylos** [comment]
Thanks Soheel. I started a Known Issues section of the readme to mention this. Do you have any tips on how to reproduce this issue without a Korean computer, or otherwise identify the code causing the bug? I looked for a Korean-specific distribution of Python 3.x on pyenv and on Google but haven't found any Korean versions or any bug reports for other modules with hints of how to identify and address the issue.

**Comment by jsstylos** [comment]
Closing this and will re-open if anyone can repo it.
