### ISSUE TITLE
bulk upload to discovery service using python-sdk?

### ISSUE THREAD

**Issue by breathe** [watson-developer-cloud/python-sdk#315]
Is bulk updating of documents possible?  Incurring network round-trip cost for each document update request seems likely to be slower than necessary ...  Especially with the synchronous design of the python sdk ...

**Comment by ammardodin** [comment]
@breathe The `update_document` method itself is asynchronous, such that once you upload a document you basically get an `id` while the service processes your update document. As such, I think the difference in speed between bulk uploading versus using an iterative approach is likely to be minute.

Although you're incurring a round-trip cost for each document upload, the bulk upload will also need a longer time since now we're uploading a much larger file. I don't think we're likely to see any significant improvement through the bulk update.
