### ISSUE TITLE
Allow voice recording for the Speech to Text service

### ISSUE THREAD

**Issue by tanmayb123** [watson-developer-cloud/python-sdk#45]
I think we should also allow users to record audio for Speech to Text, not just use a file.

Please give me some ideas.

**Comment by alienbaby** [comment]
Do you mean stream to the service? Or more a front end app that records and uploads a file as well as just asking the user for a pre recorded file?
I think we should also allow users to record audio for Speech to Text, not just use a file.

Please give me some ideas.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/watson-developer-cloud/python-sdk/issues/45

**Comment by tanmayb123** [comment]
I meant that it should be able to record to a file, then send to the service, instead of the user having to do it.
As far as I know, the Speech to Text service does not allow streaming audio?

**Comment by jsstylos** [comment]
The service itself and the Python SDK support streaming audio, although we don't have a sample that shows the streaming audio input (and this will likely require additional dependencies to interact with a microphone). The `audio` input to the `recognize` method can be either a file or file-like object, which might be streamed from a microphone.
