### ISSUE TITLE
What is the meanig of  "sampling_error"  in personality_insights_v2.py?

### ISSUE THREAD

**Issue by dapsjj** [watson-developer-cloud/python-sdk#487]
I use "Personality Insights",I find the print result "sampling_error" in  personality_insights_v2.py,but what is the meanig of "sampling_error"?Please explain in detail.

**Comment by jeffpk62** [comment]
@dapsjj That's the old way that Personality Insights communicated its confidence in the results.  You're seeing that field because you're using version 2 of the service, which was replaced by version 3 in October 2016.  There is no longer any documentation available for the version 2 interface.

Please consider moving to the version 3 interface, `personality_insights_v3.py`. This version improves the quality of its results. It provides an Average Mean Absolute Error (MAE) and Average Correlation that apply to the results for all languages.  For more information, see

- [Providing sufficient input](https://console.bluemix.net/docs/services/personality-insights/input.html#sufficient), which introduces the concepts and provides guidance for providing a sufficient number of words for meaningful results.
- [How precise is the service](https://console.bluemix.net/docs/services/personality-insights/science.html#researchPrecise), which elaborates on the Average MAE and Correlation, and provides per-language values for both characteristics.

I hope this helps!
