### ISSUE TITLE
Where to get SERVICE USERNAME and SERVICE PASSWORD

### ISSUE THREAD

**Issue by joshualimpj** [watson-developer-cloud/python-sdk#652]
I cannot seem to find the username and password in the service credentials.

**Comment by w0o** [comment]
Hi @joshualimpj , 
I'm guessing you have a recently created IBM Cloud service which would not have username and password for credentials since Cloud Foundry style credentials have been replaced with IAM API keys. You should be using IAM API keys and pass the API key as the `iam_apikey` parameter for your service.
Hope it helps.

**Comment by joshualimpj** [comment]
Thank you for the swift reply!! It's working now.
