### ISSUE TITLE
Using API key does not work in Notebooks in Watson Studio or Compare and Comply.

### ISSUE THREAD

**Issue by enebab** [watson-developer-cloud/python-sdk#679]
We have a customer using COS to store files for Watson Studio and Compare & Comply.  

When an API key is specified, it cannot be found by Notebooks in Watson Studio or Compare and Comply for some reason.

They are using COS to store files for Watson Studio and Compare & Comply.   This was working before but the problem started this week.

The COS  location is: 
https://cloud.ibm.com/objectstorage/crn%3Av1%3Abluemix%3Apublic%3Acloud-object-storage%3Aglobal%3Aa%2Fc6df3028f392004f82fda21b5c188a61%3A2ee9af4c-028f-4df3-8e80-f737abb54582%3A%3A?paneId=credentials

The specific bucket is in us-south. The bucket details are:
cosLocation = 's3.private.us-south.cloud-object-storage.appdomain.cloud'
bucketLocation = 'us-south'
cosInputBucket = 'arvind-sathi-source-10k-data'
cosOutputBucket = 'arvind-sathi-doc-decomposition'

The COS URL is:
https://cloud.ibm.com/objectstorage/crn%3Av1%3Abluemix%3Apublic%3Acloud-object-storage%3Aglobal%3Aa%2Fc6df3028f392004f82fda21b5c188a61%3A2ee9af4c-028f-4df3-8e80-f737abb54582%3A%3A?paneId=endpoint

**Comment by enebab** [comment]
Is there an update to this issue?

The customer is getting frustrated with the lack of response

**Comment by usa-at-ibm** [comment]
This GitHub issue is opened due to a Sev.1 IBM ServiceNow ticket.   CS0476371.

Please provide a response to the customer at the earliest.

Thanks.

**Comment by ehdsouza** [comment]
Hi, fill out the issue template to help you further, please include the code snippets:

**Overview**
_What is the issue? Be concise and clear._

**Expected behavior**
_What did you expect to happen?_

**Actual behavior**
_What actually happened?_

**How to reproduce**
_Help us to reproduce what you experienced. Include your code snippets (without credentials)_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
_Please provide the SDK version here._

**Additional information:**
- OS: _for example, iOS_
- Which version of `Python` are you using?

**Additional context**
_Add any other details about the problem._

**Comment by usa-at-ibm** [comment]
@enebab ^^^

**Comment by usa-at-ibm** [comment]
@ehdsouza please refer to following slack discussion. 
https://ibm-cloudplatform.slack.com/archives/C3QSKU65U/p1564158036159300

@enebab can you please work with customer and Watson Studio Support to make progress on this issue.    Thanks.

**Comment by ehdsouza** [comment]
Based on the error message, it looks like incorrect apikey is passed. Make sure the key exists and the initialization is correct. Here are tested examples: https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/compare_comply_v1.py

```
compare_comply = CompareComplyV1(
    version='2018-03-23',
    ## url is optional, and defaults to the URL below. Use the correct URL for your region.
    url='https://gateway.watsonplatform.net/compare-comply/api',
    iam_apikey='YOUR APIKEY')
```
