### ISSUE TITLE
I was trying to run ibm watson tone analysis api and i got this type of error

### ISSUE THREAD

**Issue by imshalinshah** [watson-developer-cloud/python-sdk#685]
WatsonApiException                        Traceback (most recent call last)
<ipython-input-13-54ab3754d147> in <module>
      5 tone = tone_analyzer.tone(
      6     {'text': ". ".join(text_B)},
----> 7     content_type='application/json'
      8 ).get_result()
      9 

~\Anaconda3\lib\site-packages\watson_developer_cloud\tone_analyzer_v3.py in tone(self, tone_input, content_type, sentences, tones, content_language, accept_language, **kwargs)
    205             params=params,
    206             data=data,
--> 207             accept_json=True)
    208         return response
    209 

~\Anaconda3\lib\site-packages\watson_developer_cloud\watson_service.py in request(self, method, url, accept_json, headers, params, json, data, files, **kwargs)
    585             error_info = self._get_error_info(response)
    586             raise WatsonApiException(response.status_code, error_message,
--> 587                                      info=error_info, httpResponse=response)

WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401

**Comment by ehdsouza** [comment]
@imshalinshah could you follow the issue template to let us help you better?

**Overview**
_What is the issue? Be concise and clear._

**Expected behavior**
_What did you expect to happen?_

**Actual behavior**
_What actually happened?_

**How to reproduce**
_Help us to reproduce what you experienced. Include your code snippets (without credentials)_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
_Please provide the SDK version here._

**Additional information:**
- OS: _for example, iOS_
- Which version of `Python` are you using?

**Additional context**
_Add any other details about the problem._

**Comment by ehdsouza** [comment]
@imshalinshah can you provide more information in the issue template?
